Basics
eBashura/fixed_1 pull request #1
Opened 2023-02-27 19:13 UTC by eBashura

2023-03-01 17:03 UTC, maks1makrov requested changes
4 задание неправильно, удали файл, сохрани изменения и запуш изменения на гитхаб, либо просто подожди следующего занятия

2023-03-07 07:40 UTC, maks1makrov commented on basics/basics_08.py
> +V_kuba = a ** 3
лучше писать все буквы маленькими символами

2023-03-07 07:58 UTC, maks1makrov approved these changes
исправь замечания и можешь вмерживать

2023-03-07 07:58 UTC, maks1makrov commented on basics/basics_10.py
> +c = (a ** 2) + (b ** 2)
неправильно, - надо корень еще извлечь

2023-03-07 07:58 UTC, maks1makrov commented on basics/basics_12.py
> +a1 = int(a1)
Примечание: после ввода переменных преобразовать переменные к типу int
а ты сначала приводишь к float и потом к int
сразу в int преобразуй

2023-03-07 07:58 UTC, maks1makrov commented on basics/basics_13.py
> +A1 = a1 * 2
А1 - не лучшее решение для названия переменной , тем более что уже есть а1

2023-03-11 09:09 UTC, eBashura commented on basics/basics_08.py
> +V_kuba = a ** 3
учту

2023-03-11 09:18 UTC, eBashura commented
замечания исправил

2023-05-25 17:52 UTC, merged