Strings
eBashura/fixed_1 pull request #2
Opened 2023-02-28 17:32 UTC by eBashura

2023-03-01 17:36 UTC, maks1makrov requested changes

2023-03-01 17:36 UTC, maks1makrov commented on strings/strings_01.py
> +print('Привет, меня зовут ' + firstname + ' ' + lastname + ', мне ' + age + ' лет')
в отдельную переменную сохрани строку и уже ее выводи и соответственно считай длину

2023-03-06 14:58 UTC, maks1makrov approved these changes

2023-03-11 09:19 UTC, eBashura commented on strings/strings_01.py
> +print('Привет, меня зовут ' + firstname + ' ' + lastname + ', мне ' + age + ' лет')
исправил

2023-05-25 17:53 UTC, merged