Structured prog
eBashura/fixed_1 pull request #4
Opened 2023-03-12 21:36 UTC by eBashura

2023-03-13 15:04 UTC, maks1makrov approved these changes

2023-03-19 21:42 UTC, eBashura commented
20 и 22 не сделал, буду на занятии разбираться со всеми

2023-03-19 22:00 UTC, eBashura commented
22 сейчас сделал сырой вариант задания, на занятии буду доделывать с time

2023-03-20 13:14 UTC, maks1makrov requested changes

2023-03-20 13:14 UTC, maks1makrov commented on structured_prog/structured_prog_17.py
> +for a in range(len(my_list) - 1):
тут не учитывает последний элемент, соответственно если последний будет четный - не заменит на максимальный

2023-03-20 13:14 UTC, maks1makrov commented on structured_prog/structured_prog_18.py
> +for a in range(len(my_list) - 1):
Определить количество участков массива, на котором элементы монотонно возрастают, т.е. 1, 2, 3, 4 - это один участок а не 4 участка

2023-03-29 17:07 UTC, eBashura commented on structured_prog/structured_prog_17.py
> +for a in range(len(my_list) - 1):
сделал

2023-03-29 17:13 UTC, eBashura commented on structured_prog/structured_prog_18.py
> +for a in range(len(my_list) - 1):
тут сидел думал, но у меня не правильно считает, хоть и вносил другое условие счета...

2023-04-02 08:44 UTC, maks1makrov approved these changes

2023-04-02 08:44 UTC, maks1makrov commented on structured_prog/structured_prog_18.py
> +for a in range(len(my_list) - 1):
https://github.com/miks1989/tms87-1/blob/struct_prog/struct_prog/struct_prog_18.py

2023-04-02 19:31 UTC, maks1makrov approved these changes

2023-05-25 17:53 UTC, merged