Loops
eBashura/fixed_1 pull request #5
Opened 2023-03-13 09:27 UTC by eBashura

задания loops 
09 и 10 выводит в один столбец, как поправить это?
11 как вывести кол-во семерок, просмотрел все лекции, но что-то не понимаю
12 и 14 вообще не понимаю как делать
13 как вывести нужные фамилии, тоже просмотрел лекции все, но не понимаю
15 как прописать диапазон в котором искать число, также не понимаю
все "непонималки" гуглил но то, что написано в гугле, мне непонятно 
по остальным вроде разобрался

2023-03-16 09:34 UTC, maks1makrov requested changes

2023-03-16 09:34 UTC, maks1makrov commented on loops/loops_04.py
> +    if num != stop_word:
if в 13 строке можно убрать

2023-03-16 09:34 UTC, maks1makrov commented on loops/loops_08.py
> +for i in range(a, b + 1):
ты уже создал r , так и используй его дальше
for i in r:

2023-03-16 09:34 UTC, maks1makrov commented on loops/loops_13.py
> +for i, j in enumerate(surname_list):
не надо тут enumerate
просто проитерируй по списку и у каждого элемента (строка) проверь первый и последний символ

2023-03-19 21:44 UTC, eBashura commented on loops/loops_04.py
> +    if num != stop_word:
исправил

2023-03-19 21:45 UTC, eBashura commented on loops/loops_08.py
> +for i in range(a, b + 1):
исправил

2023-03-19 21:46 UTC, eBashura commented on loops/loops_13.py
> +for i, j in enumerate(surname_list):
исправил

2023-03-20 13:05 UTC, maks1makrov approved these changes

2023-05-25 17:53 UTC, merged