Arr tg
eBashura/fixed_1 pull request #7
Opened 2023-03-13 11:37 UTC by eBashura

03 неправильно считает геом среднее
04,05,06 не понимаю как
07 сделал без while

2023-03-13 15:07 UTC, maks1makrov requested changes

2023-03-13 15:07 UTC, maks1makrov commented on extra_zadacha/arr_07.py
> +print(len(arr))
надо вначале отсортировать

2023-03-29 17:04 UTC, eBashura commented on extra_zadacha/arr_07.py
> +print(len(arr))
отсортировал

2023-04-02 09:06 UTC, maks1makrov approved these changes

2023-04-02 09:06 UTC, maks1makrov commented on extra_zadacha/arr_04.py
> +# 4. Найти массив квадратов
это значит надо получить новый список где каждый элемент возведен в квадрат

2023-05-25 17:54 UTC, merged